stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - runner-bimsys  # Le tag de ton runner local
  only:
    - main
  script:
    - echo "Déploiement local dans dossier monté..."   
    - sudo docker compose -f docker.compose.local.yml build bimsys
    - sudo docker compose -f docker.compose.local.yml up -d
  environment:
    name: production
