stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - runner-bimsys
  only:
    - main
  image: docker/compose:1.29.2
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - echo "Déploiement local dans dossier monté..."
    - docker info
    - docker-compose -f docker.compose.local.yml up -d --build
  environment:
    name: production
  before_script:
    - whoami
    - id
  privileged: true
