stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - runner-bimsys
  only:
    - main
  script:
    - echo "Déploiement local en cours..."
    - cd /home/adm-bim/dev/bimsys
    - git pull
    - sudo docker compose -f docker.compose.local.yml build bimsys
    - sudo docker compose -f docker.compose.local.yml up -d
  environment:
    name: production
