stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - runner-bimsys 
  only:
    - main
  script:
    - echo "Déploiement local dans dossier monté..."  
     
    -  docker-compose -f docker.compose.local.yml up -d --build
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  environment:
    name: production
  privileged: true
