stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - echo "Déploiement en cours sur le serveur distant..."
    - apk add --no-cache openssh 
    - chmod 600 $SSH_PRIVATE_KEY
    - eval $(ssh-agent -s)
    - ssh-add $SSH_PRIVATE_KEY
    - ssh -p 22  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
        cd ~/dev/bimsys
        git pull
        sudo docker compose -f  docker.compose.local.yml build bimsys
        sudo docker compose -f  docker.compose.local.yml up -d
      EOF
  variables:
    GIT_STRATEGY: none
  environment:
    name: production
