stages:
  - build

build_app:
  stage: build
  tags:
    - runner-bimsys
  image: docker:20.10.16

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375

  script:
    - apk add --no-cache py3-pip
    - pip install docker-compose
    - docker info
    - docker-compose -f docker.compose.local.yml up -d --build

  only:
    - main

  environment:
    name: production
