services:

  bimsys:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 83
        
    container_name: bimsys
    volumes:
      - .:/bimsys  # MONTER le dossier local dans le conteneur

    ports:
      - "82:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/app.py