services:

  bimsys:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 83
    container_name: bimsys 
    ports:
      - "83:5000"
    environment:
      - FLASK_ENV=development