"""Initial

Revision ID: 0cc7b99d54e3
Revises: 
Create Date: 2025-06-09 16:24:46.330205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc7b99d54e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_phases')
    # op.drop_table('_alembic_tmp_project_phases')
    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    with op.batch_alter_table('project_phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('euros_budget', sa.Float(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('is_archived')

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'project_phases', ['project_phase_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project_phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('euros_budget')
        batch_op.drop_column('days_budget')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    op.create_table('_alembic_tmp_project_phases',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('phase_id', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # op.create_table('_alembic_tmp_phases',
    # sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id')
    # )
    # ### end Alembic commands ###
