"""add date in dailyworklaod 2

Revision ID: 277854dcb2c6
Revises: 690b34a7107f
Create Date: 2025-09-02 14:45:36.826438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277854dcb2c6'
down_revision = '690b34a7107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_workload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('daily_workload', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
