"""add assigned by

Revision ID: 27af66486592
Revises: 277854dcb2c6
Create Date: 2025-09-04 09:30:10.715679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27af66486592'
down_revision = '277854dcb2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('projects', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk assigned by", 'BimUsers', ['assigned_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_by')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
