"""new tasks tables

Revision ID: 2d2a227b11c4
Revises: dafc1f0c3d91
Create Date: 2025-06-15 13:43:20.686645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2a227b11c4'
down_revision = 'dafc1f0c3d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('Standard_task')
    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_task_id', sa.String(length=16), nullable=True))
        batch_op.create_foreign_key("tset1", 'standard_tasks', ['standard_task_id'], ['id'])
        batch_op.create_foreign_key("test2", 'project_phases', ['project_phase_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('standard_task_id')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    op.create_table('Standard_task',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('estimated_days', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
