"""updates

Revision ID: 2fb9ced6303a
Revises: 29260ad5b715
Create Date: 2025-07-14 18:59:27.702059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb9ced6303a'
down_revision = '29260ad5b715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        # batch_op.drop_constraint("foreignkey", type_='foreignkey')
        batch_op.drop_column('phase')
        batch_op.drop_column('bim_manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bim_manager_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'BimUsers', ['bim_manager_id'], ['id'])

    # ### end Alembic commands ###
