"""update task table

Revision ID: 3c27cc9f6291
Revises: 2d2a227b11c4
Create Date: 2025-06-26 16:22:24.477162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c27cc9f6291'
down_revision = '2d2a227b11c4'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('custom_tasks', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('task_id')

    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('custom_task_id', sa.String(length=16), nullable=True))
    #     # batch_op.create_foreign_key( 'custom_tasks_update', ['custom_task_id'], ['id'])

    # # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('custom_task_id')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('custom_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=16), nullable=False))
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
