"""add category2 in task

Revision ID: 41ff2e295ed3
Revises: 8e1a5cdd2a2d
Create Date: 2025-07-01 15:58:58.216880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ff2e295ed3'
down_revision = '8e1a5cdd2a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category2', sa.Text(), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.TEXT(), nullable=True))
        batch_op.drop_column('category2')
        batch_op.drop_column('category1')

    # ### end Alembic commands ###
