"""update task_days_budget and costum_days_budjet in project phases

Revision ID: 619f92968ac9
Revises: 4b00c803a58f
Create Date: 2025-07-12 14:25:19.609436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619f92968ac9'
down_revision = '4b00c803a58f'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('project_phases', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('costum_days_budget', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('tasks_days_budget', sa.Float(), nullable=True))

    # # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_phases', schema=None) as batch_op:
        batch_op.drop_column('tasks_days_budget')
        batch_op.drop_column('costum_days_budget')

    # ### end Alembic commands ###
