"""add date in dailyworklaod

Revision ID: 690b34a7107f
Revises: c949db37b069
Create Date: 2025-09-02 14:07:06.443377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690b34a7107f'
down_revision = 'c949db37b069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_workload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # with op.batch_alter_table('projects', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('daily_workload', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
