"""add category to taks


Revision ID: 8e1a5cdd2a2d
Revises: ab4999f5ea80
Create Date: 2025-07-01 15:37:56.886232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1a5cdd2a2d'
down_revision = 'ab4999f5ea80'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('standard_tasks', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('category', sa.Text(), nullable=True))

    # with op.batch_alter_table('workload', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_user_phase_week', ['bimuser_id', 'project_phase_id', 'week'])

    # # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phase_week', type_='unique')

    with op.batch_alter_table('standard_tasks', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
