"""maj project table

Revision ID: 9fabcc33a9c1
Revises: 82ceb0c7ab14
Create Date: 2025-04-11 11:53:42.780628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fabcc33a9c1'
down_revision = '82ceb0c7ab14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('days_budget')

    # ### end Alembic commands ###
