""" no constrain on code_akuiteo

Revision ID: a1b4f115d2d1
Revises: 2fb9ced6303a
Create Date: 2025-07-20 18:25:52.235831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b4f115d2d1'
down_revision = '2fb9ced6303a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_project_phases')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('code_akuiteo',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('code_akuiteo',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    op.create_table('_alembic_tmp_project_phases',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('days_budget', sa.FLOAT(), nullable=True),
    sa.Column('euros_budget', sa.FLOAT(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('phase_id', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('assigned_bimuser_id', sa.VARCHAR(length=16), nullable=True),
    sa.Column('costum_days_budget', sa.FLOAT(), nullable=True),
    sa.Column('tasks_days_budget', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_bimuser_id'], ['BimUsers.id'], name='fk_projectphase_user'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_projectphase_project', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
