"""update costum task in task

Revision ID: ab4999f5ea80
Revises: 3c27cc9f6291
Create Date: 2025-06-26 16:43:02.628275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4999f5ea80'
down_revision = '3c27cc9f6291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('custom_tasks', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('estimated_days', sa.Float(), nullable=True))
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('task_id')

    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.create_foreign_key("custom_tasks", 'custom_tasks', ['custom_task_id'], ['id'])

    # # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('custom_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=16), nullable=False))
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('estimated_days')

    # ### end Alembic commands ###
