"""Add project_phase_id to tasks

Revision ID: c3eadd1f5a4f
Revises: 5bde56313aca
Create Date: 2025-05-09 15:16:37.663635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eadd1f5a4f'
down_revision = '5bde56313aca'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    # with op.batch_alter_table('project_phases', schema=None) as batch_op:
    #     batch_op.drop_column('is_archived')
    #     batch_op.drop_column('start_date')
    #     batch_op.drop_column('status')
    #     batch_op.drop_column('end_date')

    # simple ADD COLUMN; no batch mode
    op.add_column(
        'tasks',
        sa.Column('project_phase_id', sa.String(length=16), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_phase_id')

    with op.batch_alter_table('project_phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
