"""bimusers updates

Revision ID: c8d83600742e
Revises: 0c91c94a089b
Create Date: 2025-07-27 10:13:41.118682

"""
from alembic import op
import sqlalchemy as sa
from database.model import BimUsers
from database.db import db

# revision identifiers, used by Alembic.
revision = 'c8d83600742e'
down_revision = '0c91c94a089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('BimUsers', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False))

    # with op.batch_alter_table('projects', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['id'])


    users_data = [
    ("Youssef", "Mrabet", "youssef.mrabet@arep.fr", "BIM MANAGER", None, 750),
    ("Anna-Lucia", "Uribe", "annalucia.uribe@arep.fr", "BIM MANAGER", None, 750),
    ("Mohamed", "Asli", "mohamed.asli@arep.fr", "BIM MANAGER", None, 750),
    ("Joaquin", "Gisner", "joaquin.gisner@arep.fr", "BIM MANAGER", None, 750),
    ("Sarra", "Cuccu", "sarra.cuccu@arep.fr", "BIM MANAGER", None, 750),
    ("Liliane-Evangelia", "Bompoulou", "evangelia.bompolou@arep.fr", "BIM MANAGER", None, 750),
    ("Aurélie", "Estorge", "aurelie.estorge@arep.fr", "BIM MANAGER", None, 750),
]

    # for first, last, email, role, password, taj in users_data : 
    #     u = BimUsers(name=first, lastname=last, email=email, role=role, password=password, taj=taj)
    #     db.session.add(u)

    # db.session.commit()
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('projects', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='unique')

    # with op.batch_alter_table('BimUsers', schema=None) as batch_op:
    #     batch_op.drop_column('prenom')
    pass
    # ### end Alembic commands ###
