"""project_phasses status

Revision ID: c949db37b069
Revises: 6dedad35bed5
Create Date: 2025-08-08 09:28:27.007880

"""
from alembic import op
import sqlalchemy as sa
from database.model import ProjectPhase , Project
from database.db import db 

from datetime import date


# revision identifiers, used by Alembic.
revision = 'c949db37b069'
down_revision = '6dedad35bed5'
branch_labels = None
depends_on = None
today = date.today()


def upgrade():
    today = date.today()

    project_phases = ProjectPhase.query.all()
    for pp in project_phases:
        if today < pp.start_date:
            pp.status = "Non commencé"
        elif today > pp.end_date:
            pp.status = "Terminé"
        else:
            pp.status = "En cours"

    db.session.commit()

    projects = Project.query.all()
    for p in projects:
        phase_statuses = [phase.status for phase in p.phases if phase.status]

        if not phase_statuses:
            p.status = "Non commencé"
        elif "En cours" in phase_statuses:
            p.status = "En cours"
        elif all(s == "Non commencé" for s in phase_statuses):
            p.status = "Non commencé"
        elif all(s == "Terminé" for s in phase_statuses):
            p.status = "Terminé"
        else:
            p.status = "Non commencé" 

    db.session.commit()




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
