"""test

Revision ID: dafc1f0c3d91
Revises: 259f4e91102b
Create Date: 2025-06-15 12:23:31.175538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafc1f0c3d91'
down_revision = '259f4e91102b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_phases')
    with op.batch_alter_table('BimUsers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taj', sa.Integer(), nullable=True))

    # with op.batch_alter_table('phases', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_column('project_id')

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'project_phases', ['project_phase_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('BimUsers', schema=None) as batch_op:
        batch_op.drop_column('taj')

    op.create_table('_alembic_tmp_phases',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
